<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
           

    function index()
    {

        $data['_view'] = 'index';
        $this->load->view('template/main',$data);
        // $this->load->view('welcome');
    }
    function panel()
    {
        $data['_view'] = 'dashboard/dashboard';
        $this->load->view('layout/main',$data);
    }
    function account()
    {
        $data['_view'] = 'account';
        $this->load->view('template/main',$data);
    }
    function plans()
    {
        $data['_view'] = 'plans';
        $this->load->view('template/main',$data);
    }
    function terms()
    {
        $data['_view'] = 'terms';
        $this->load->view('template/main',$data);
    }
    function privacy()
    {
        $data['_view'] = 'privacy';
        $this->load->view('template/main',$data);
    }

    function logout()
    {
        $this->session->sess_destroy();
        redirect('');
    }


    function nopower()
    {
        $data['_view'] = 'nopower';

        $this->load->view('template/main',$data);
    }

}
