<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Upload_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->admissionID = $this->session->userdata('admissionID');
    }
    
    /*
     * Get upload by uploadId
     */
    function get_upload($uploadId)
    {

        $this->db->where('admissionID', $this->admissionID);
        return $this->db->get_where('upload',array('uploadId'=>$uploadId))->row_array();
    }
        
    /*
     * Get all upload
     */
    function get_all_upload()
    {
        $this->db->where('admissionID', $this->admissionID);
        $this->db->order_by('uploadId', 'desc');
        return $this->db->get('upload')->result_array();
    }
        
    /*
     * function to add new upload
     */
    function add_upload($params)
    {
        $this->db->insert('upload',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update upload
     */
    function update_upload($uploadId,$params)
    {
        $this->db->where('admissionID', $this->admissionID);
        $this->db->where('uploadId',$uploadId);
        return $this->db->update('upload',$params);
    }
    
    /*
     * function to delete upload
     */
    function delete_upload($uploadId)
    {
        $this->db->where('admissionID', $this->admissionID);
        return $this->db->delete('upload',array('uploadId'=>$uploadId));
    }
}
